openapi: 3.0.0
info:
  title: Community Connect API
  description: API documentation for Community Connect
  version: 1.0.0

servers:
  - url: http://localhost:5555

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User successfully registered
        "400":
          description: Bad request

  /api/auth/login:
    post:
      summary: Login a user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
        "401":
          description: Unauthorized

  /api/auth/me:
    get:
      summary: Get user profile (Protected)
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User profile retrieved
        "401":
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
